server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

zuul:
  prefix: /api # 添加路由前缀
  routes:
   item-service: /item/** #将商品微服务映射到/item/**
   upload-service:  #将上传微服务映射到/upload/**
   #忽略/upload/**
     path: /upload/**
     serviceId: upload-service
     strip-prefix: false
   search-service: /search/** # 搜索微服务
   page-service: /page/**    # 商品详情微服务
   user-service: /user/**  # 用户微服务
   auth-service: /auth/** # 授权中心微服务
   cart-service: /cart/** # 购物车微服务
   order-service: /order/** # 订单微服务
  add-host-header: true  #携带请求本身的head头信息
  sensitive-headers:     # 配置禁止使用头信息，这里设置为null，否则set-cookie无效
ribbon:
  ConnectTimeout: 60000 # 连接超时时间(ms)
  ReadTimeout: 60000 # 通信超时时间(ms)
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
  MaxAutoRetries: 0 # 同一实例的重试次数


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 5000 # 熔断超时时长：5000ms
ly:
  jwt:
    pubKeyPath: D:\\heima\\rsa\\rsa.pub # 公钥地址
    CookieName: LY_TOKEN
    CookieMaxage: 1800
  # 白名单不被拦截
  filter:
      allowPaths:
        - /api/auth
        - /api/search
        - /api/user/register
        - /api/user/check
        - /api/user/code
        - /api/item
